version: '3'

services:
  postgres:
    image: postgres:16-alpine
    container_name: comp1640
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: comp1640
      POSTGRES_USER: user
      POSTGRES_PASSWORD: abcdef
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: